name: Pass/Fail GHA

on: workflow_dispatch
env:
  API_ID: ${{ secrets.VERACODE_API_ID }}
  API_KEY: ${{ secrets.VERACODE_API_KEY }}
  APP_NAME: VeraGHA

jobs:

  get_pass_fail_info:
    runs-on: ubuntu-latest
    container:
      image: veracode/api-wrapper-java:latest
    steps: 
      - name: get pass/fail info
        run: |
          cd /tmp
          java -jar /opt/veracode/api-wrapper.jar -vid ${{ secrets.VERACODE_API_ID }} -vkey ${{ secrets.VERACODE_API_KEY }} -action passfail -appname ${{ env.APP_NAME }} > passfail.txt
          if echo "cat passfail.txt" | grep -q "Did Not Pass"; then
            echo "The scan did not pass policy"
            exit 1
          else 
            echo "The scan did pass policy"
          fi

      

