

name: AC

on:
  workflow_dispatch:
  
jobs:
  Maven_Build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
        
  # build the application
    - uses: actions/setup-java@v1 # Make java accessible on path so the uploadandscan action can run.
      with: 
        java-version: '8'

    - name: Build with Maven
      run: mvn -B package --file app/pom.xml

      
    - name: Archive package
      uses: actions/upload-artifact@v2
      with:
        name: CodePackage
        path: '**/*.war'
  
  Pipeline_Scan: 
    needs: Maven_Build
    runs-on: ubuntu-latest

    
    steps:
    - name: Retrieve artifact
      uses: actions/download-artifact@v2
      with:
        name: CodePackage
        path: .
        
    - name: Pipeline Scan
      continue-on-error: true
      run: |
        wget https://downloads.veracode.com/securityscan/pipeline-scan-LATEST.zip
        unzip -o -d /tmp pipeline-scan-LATEST.zip
        ls -la
        #chmod +r *.war
        #java -jar /tmp/pipeline-scan.jar --veracode_api_id "${{ secrets.VERACODE_API_ID }}" --veracode_api_key "${{ secrets.VERACODE_API_KEY }}" --request_policy "Test"
        #java -jar /tmp/pipeline-scan.jar --veracode_api_id "${{ secrets.VERACODE_API_ID }}" --veracode_api_key "${{ secrets.VERACODE_API_KEY }}" --fail_on_severity="Very High, High" --file "/home/runner/work/verademo/verademo/verademo.war"
      
    - uses: actions/upload-artifact@v2
      name: upload reports
      with:
        name: veracode-results
        path: ./results.json
