name: Policy Status Script

on: workflow_dispatch
env:
  API_ID: ${{ secrets.VERACODE_API_ID }}
  API_KEY: ${{ secrets.VERACODE_API_KEY }}
  APP_NAME: VeraGHA

jobs:

  get_ploicy_status:
    runs-on: ubuntu-latest
    container:
      image: veracode/api-signing:latest
    steps: 
      - name: get policy status
        run: |
          cd /tmp
          export VERACODE_API_KEY_ID=${{ env.API_ID }}
          export VERACODE_API_KEY_SECRET=${{ env.API_KEY }}
          echo "{\"name\":\"Pre Scan Test\",\"schedule\":{\"duration\":{\"length\":1,\"unit\":\"DAY\"},\"scheduled\":true,\"now\":true}}" > input.json
          cat input.json
          ID=$(http --auth-type veracode_hmac GET "https://api.veracode.com/was/configservice/v1/analyses?name=${{ env.Analyses_Name }}" | jq -r '._embedded.analyses[0].analysis_id')
          echo ID:${ID}
    

  
