name: Veracode SCA Agent Demo
on:
  pull_request:
    branches: [ feature, main ]

jobs: 
  SCA: 
    name: Software Composition Analysis
    runs-on: ubuntu-latest
    env: 
        SRCCLR_API_TOKEN: ${{ secrets.SRCCLR_API_TOKEN }}
        SCAN_DIR: "./app"
    steps:
        - name: Check out branch
          uses: actions/checkout@v2
          
        - name: Veracode Dependency Scanning
          run: |
              curl -sSL https://download.sourceclear.com/ci.sh | bash -s scan --update-advisor > results.txt
              cat results.txt
              
          
          
