name: Summary Report

on:
#  push:
#    branches: [ main ]
#  pull_request:
#    branches: [ main ]
    workflow_dispatch: 

env:
  API_ID: ${{ secrets.VERACODE_API_ID }}
  API_KEY: ${{ secrets.VERACODE_API_KEY }}
  APP_NAME: VeraGHA

jobs: 
  veracode-api-call:
    runs-on: ubuntu-latest
  
    steps:
    - name: Get Application GUID for Verademo One
      id: get_guid
      env: 
        API_ID: ${{ secrets.VERACODE_API_ID }}
        API_KEY: ${{ secrets.VERACODE_API_KEY }}
      run: |
        GUID=$(docker run --rm \
          -e VERACODE_API_KEY_ID=${{ env.API_ID }} \
          -e VERACODE_API_KEY_SECRET=${{ env.API_KEY }} \
          veracode/api-signing \
          http --auth-type veracode_hmac GET \
          https://api.veracode.com/appsec/v1/applications/?name=${{ env.APP_NAME }} \
          | jq -r '._embedded.applications[0].guid')
        echo "$GUID" > app_id.txt
    
    - name: Set env creds
      run: |
        echo "APP_ID=$(cat app_id.txt)" >> $GITHUB_ENV
    
    
    - name: Verify_Variable
      run: echo "APP_ID=$APP_ID"
      
    - name: Get_Summary_Report
      env: 
        API_ID: ${{ secrets.VERACODE_API_ID }}
        API_KEY: ${{ secrets.VERACODE_API_KEY }}
      run: |
        docker run --rm \
          -e VERACODE_API_KEY_ID=${{ env.API_ID }} \
          -e VERACODE_API_KEY_SECRET=${{ env.API_KEY }} \
          veracode/api-signing \
          http --auth-type veracode_hmac GET \
          https://api.veracode.com/appsec/v1/applications/${{ env.APP_ID }}/summary_report \
  
      
          
          
