name: Summary Report GHA

on: workflow_dispatch
env:
  API_ID: ${{ secrets.VERACODE_API_ID }}
  API_KEY: ${{ secrets.VERACODE_API_KEY }}
  APP_NAME: VeraGHA

jobs:

  get_summary_report:
    runs-on: ubuntu-latest
    container:
      image: veracode/api-signing:latest
    steps: 
      - name: get summary report
        run: |
          cd /tmp
          export VERACODE_API_KEY_ID=${{ env.API_ID }}
          export VERACODE_API_KEY_SECRET=${{ env.API_KEY }}
          GUID=$(http --auth-type veracode_hmac GET "https://api.veracode.com/appsec/v1/applications/?name=${{ env.APP_NAME }}" | jq -r '._embedded.applications[0].guid')
          echo GUID: ${GUID}
          http --auth-type veracode_hmac GET "https://api.veracode.com/appsec/v2/applications/$GUID/summary_report" > summary.json
      
      - name: save summary file
        uses: actions/upload-artifact@v2
        with: 
          name: summary-report
          path: /summary.json 

  
